apiVersion: v1
kind: Pod
metadata:
  name: nginx-with-service-account
  labels:
    app: nginx
spec:
  serviceAccountName: nginx-service-account
  containers:
  - name: nginx
    image: nginx:latest
    ports:
    - containerPort: 80
