apiVersion: v1
kind: Pod
metadata:
  name: nginx-security-context
  labels:
    app: nginx
spec:
  # this is applied at pod level
  securityContext:
    runAsUser: 1000
    runAsGroup: 3000
    fsGroup: 2000
  containers:
  - name: nginx
    image: nginx:latest
    ports:
    - containerPort: 80
    # this is applied at container level
    securityContext:
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: true
      runAsNonRoot: true
      capabilities:
        drop:
        - ALL
        add:
        - NET_BIND_SERVICE
