apiVersion: v1
kind: LimitRange
metadata:
  name: resource-limit-range
spec:
  limits:
  - default:
      memory: "256Mi"
      cpu: "500m"
    defaultRequest:
      memory: "128Mi"
      cpu: "250m"
    max:
      memory: "512Mi"
      cpu: "1"
    min:
      memory: "64Mi"
      cpu: "100m"
    type: Container
